server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
spring:
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
